services:
  quickwit:
    image: quickwit/quickwit
    volumes:
      - ./.data/qwdata:/quickwit/qwdata
      - ./config/quickwit.yaml:/quickwit/config/quickwit.yaml
    ports:
      - 7280:7280
    command: run

  minio:
    image: minio/minio
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/quickwit-data
        minio server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=quickwit
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    ports:
      - 9000
      - 9001:9001
    volumes:
      - ./.data/minio:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 15s
      timeout: 20s
      retries: 5
